// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANkapAIyWUhL_XijZtyz2VR_fFxXKvYoE',
    appId: '1:440298503063:web:dc6843303f5065b81862d2',
    messagingSenderId: '440298503063',
    projectId: 'itinera-ai-17bb9',
    authDomain: 'itinera-ai-17bb9.firebaseapp.com',
    storageBucket: 'itinera-ai-17bb9.firebasestorage.app',
    measurementId: 'G-X6EN2LV9Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkapAIyWUhL_XijZtyz2VR_fFxXKvYoE',
    appId: '1:440298503063:android:8faa9d6ee08e31021862d2',
    messagingSenderId: '440298503063',
    projectId: 'itinera-ai-17bb9',
    storageBucket: 'itinera-ai-17bb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANkapAIyWUhL_XijZtyz2VR_fFxXKvYoE',
    appId: '1:440298503063:ios:8faa9d6ee08e31021862d2',
    messagingSenderId: '440298503063',
    projectId: 'itinera-ai-17bb9',
    storageBucket: 'itinera-ai-17bb9.firebasestorage.app',
    iosBundleId: 'com.example.itineraAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANkapAIyWUhL_XijZtyz2VR_fFxXKvYoE',
    appId: '1:440298503063:ios:8faa9d6ee08e31021862d2',
    messagingSenderId: '440298503063',
    projectId: 'itinera-ai-17bb9',
    storageBucket: 'itinera-ai-17bb9.firebasestorage.app',
    iosBundleId: 'com.example.itineraAi',
  );
}
